// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi ollie-skill-api
Alexa custom skill service endpoints for Ollie


    Schemes:
      http
    Host: localhost:5000
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
