// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Context context
// swagger:model Context
type Context struct {

	// audio player
	AudioPlayer *AudioPlayer `json:"AudioPlayer,omitempty"`

	// system
	System *System `json:"system,omitempty"`
}

// Validate validates this context
func (m *Context) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAudioPlayer(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSystem(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Context) validateAudioPlayer(formats strfmt.Registry) error {

	if swag.IsZero(m.AudioPlayer) { // not required
		return nil
	}

	if m.AudioPlayer != nil {

		if err := m.AudioPlayer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("AudioPlayer")
			}
			return err
		}
	}

	return nil
}

func (m *Context) validateSystem(formats strfmt.Registry) error {

	if swag.IsZero(m.System) { // not required
		return nil
	}

	if m.System != nil {

		if err := m.System.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("system")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Context) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Context) UnmarshalBinary(b []byte) error {
	var res Context
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
