// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Intent intent
// swagger:model Intent
type Intent struct {

	// confirmation status
	ConfirmationStatus string `json:"confirmationStatus,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// slots
	Slots *Slots `json:"slots,omitempty"`
}

// Validate validates this intent
func (m *Intent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSlots(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Intent) validateSlots(formats strfmt.Registry) error {

	if swag.IsZero(m.Slots) { // not required
		return nil
	}

	if m.Slots != nil {

		if err := m.Slots.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("slots")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Intent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Intent) UnmarshalBinary(b []byte) error {
	var res Intent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
