// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Reprompt reprompt
// swagger:model Reprompt
type Reprompt struct {

	// output speech
	OutputSpeech *OutputSpeech `json:"outputSpeech,omitempty"`
}

// Validate validates this reprompt
func (m *Reprompt) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOutputSpeech(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Reprompt) validateOutputSpeech(formats strfmt.Registry) error {

	if swag.IsZero(m.OutputSpeech) { // not required
		return nil
	}

	if m.OutputSpeech != nil {

		if err := m.OutputSpeech.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("outputSpeech")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Reprompt) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Reprompt) UnmarshalBinary(b []byte) error {
	var res Reprompt
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
