// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Resp resp
// swagger:model Resp
type Resp struct {

	// response
	Response *Response `json:"response,omitempty"`

	// session attributes
	SessionAttributes *Attributes `json:"sessionAttributes,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this resp
func (m *Resp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResponse(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSessionAttributes(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Resp) validateResponse(formats strfmt.Registry) error {

	if swag.IsZero(m.Response) { // not required
		return nil
	}

	if m.Response != nil {

		if err := m.Response.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("response")
			}
			return err
		}
	}

	return nil
}

func (m *Resp) validateSessionAttributes(formats strfmt.Registry) error {

	if swag.IsZero(m.SessionAttributes) { // not required
		return nil
	}

	if m.SessionAttributes != nil {

		if err := m.SessionAttributes.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sessionAttributes")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Resp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Resp) UnmarshalBinary(b []byte) error {
	var res Resp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
